# Generated by Django 5.2.1 on 2025-06-01 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('269adc52-175f-42b6-b447-75565ea9fa3e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('db07d122-93e9-4216-9343-69ed0e358ab8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('5c0eba3c-ed0a-42a3-9450-28a2e0b9c29e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
